spring:

    ## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

auth:
  jwt:
    expirationSeconds: 99999999
    secure: false

server:
  servlet:
    context-path: