spring:
  application:
    name: VocabularySRS

  #PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:54320/vocabulary
    username: user
    password: admin

  ## Flyway
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/insert
    schemas: public

    ## Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


vocabulary:
  task-creator:
    scheduler: "0 0 6 * * *"