spring:
  application:
    name: VocabularySRS
  config:
    import: "optional:aws-secretsmanager:prod/vocabulary"

  #PostgreSQL
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  ## Flyway
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/insert
    schemas: public

    ## Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ## Token jwt
auth:
  jwt:
    expirationSeconds: 90
    issuer: VocabularySRS-backend
    refresh-expiration-seconds: 604800

  ## Http Dictionary Api
dictionary:
  http:
    client:
      config:
        connection-timeout: 5000
        read-timeout: 5000
        uri: https://api.dictionaryapi.dev/api/v2/entries/en/