spring:
  application:
    name: VocabularySRS
  config:
    import: "optional:aws-secretsmanager:prod/vocabulary"

  #PostgreSQL
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  ## Flyway
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/insert
    schemas: public

    ## Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

    ## Redis
  cache:
    type: redis
    redis:
      time-to-live: 24h
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

  ## Token jwt
auth:
  jwt:
    expirationSeconds: 90
    issuer: VocabularySRS-backend
    refresh-expiration-seconds: 604800
    secure: true

  ## Http Dictionary Api
dictionary:
  http:
    client:
      config:
        connection-timeout: 5000
        read-timeout: 5000
        uri: https://api.dictionaryapi.dev/api/v2/entries/en/

  ## Http Translate Api
translate:
  http:
    client:
      config:
        base-url: ${TRANSLATE_BASE_URL}
        translate-path: /translate
        connection-timeout: 5000
        read-timeout: 5000
        size-alternatives: 5
